'use client';

import { useState, useEffect } from 'react';
import { Lightbulb, Loader2, Sparkles, Filter, Pin, Trash2 } from 'lucide-react';
import { useToast } from '@/components/ui/toast';
import { InsightCard, InsightsEmptyState } from '@/components/dashboard/insight-card';
import type { Insight } from '@/lib/dashboard-client';

const CATEGORIES = [
  { value: 'ALL', label: 'All Insights' },
  { value: 'CASHFLOW', label: 'Cash Flow' },
  { value: 'CREDIT', label: 'Credit Readiness' },
  { value: 'GROWTH', label: 'Growth Opportunities' },
  { value: 'TAX', label: 'Tax & Compliance' },
] as const;

export default function InsightsPage() {
  const toast = useToast();
  const [insights, setInsights] = useState<Insight[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedCategory, setSelectedCategory] = useState<string>('ALL');

  const load = async () => {
    try {
      setLoading(true);
      const url = selectedCategory === 'ALL' 
        ? '/api/insights' 
        : `/api/insights?category=${selectedCategory}`;
      
      const res = await fetch(url, { credentials: 'include' });
      const json = await res.json();
      
      if (!res.ok || !json.success) {
        throw new Error(json.error || 'Failed to fetch insights');
      }
      
      setInsights(json.data.insights || []);
    } catch (err) {
      const error = err as Error;
      toast.error(error.message || 'Error loading financial insights');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, [selectedCategory]);

  const handlePin = async (id: string) => {
    try {
      const res = await fetch(`/api/insights/${id}/pin`, {
        method: 'PATCH',
        credentials: 'include',
      });
      const json = await res.json();
      
      if (!res.ok || !json.success) {
        throw new Error(json.error || 'Failed to toggle pin state');
      }
      
      // Update local state by flipping the pinned status and sorting pinned to the top
      setInsights(prev => {
        const updated = prev.map(item => 
          item.id === id ? { ...item, isPinned: !item.isPinned } : item
        );
        // Sort pinned items to the top, keeping date sorting otherwise
        return updated.sort((a, b) => {
          if (a.isPinned && !b.isPinned) return -1;
          if (!a.isPinned && b.isPinned) return 1;
          return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
        });
      });
      
      toast.success(json.data.insight.isPinned ? 'Insight pinned to dashboard' : 'Insight unpinned');
    } catch (err) {
      const error = err as Error;
      toast.error(error.message || 'Failed to pin insight');
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure you want to delete this insight? This action cannot be undone.')) {
      return;
    }
    
    try {
      const res = await fetch(`/api/insights/${id}`, {
        method: 'DELETE',
        credentials: 'include',
      });
      const json = await res.json();
      
      if (!res.ok || !json.success) {
        throw new Error(json.error || 'Failed to delete insight');
      }
      
      // Filter out deleted insight from local state
      setInsights(prev => prev.filter(item => item.id !== id));
      toast.success('Insight deleted successfully');
    } catch (err) {
      const error = err as Error;
      toast.error(error.message || 'Failed to delete insight');
    }
  };

  return (
    <div className="space-y-6 max-w-[1200px] animate-in fade-in duration-500">
      
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-emerald-600 shrink-0" />
            Financial Insights
          </h1>
          <p className="text-slate-500 mt-1">
            Real-time advisory updates generated by Gemini AI analyzing your cashflow history.
          </p>
        </div>
        
        {/* Quick Regeneration Banner */}
        <div className="bg-emerald-50 border border-emerald-100 rounded-lg px-4 py-2 text-xs font-semibold text-emerald-800 flex items-center gap-1.5 self-start sm:self-auto">
          <Lightbulb className="w-3.5 h-3.5 text-emerald-600 animate-pulse" />
          Updated daily based on your transaction logs
        </div>
      </div>

      {/* Categories Filter Bar */}
      <div className="flex items-center gap-2.5 overflow-x-auto pb-1.5 scrollbar-thin border-b border-slate-200">
        <Filter className="w-4 h-4 text-slate-400 shrink-0 mr-1.5" />
        {CATEGORIES.map((cat) => (
          <button
            key={cat.value}
            onClick={() => setSelectedCategory(cat.value)}
            className={`px-3 py-1.5 rounded-full text-xs font-bold whitespace-nowrap transition-all select-none border border-slate-200 ${
              selectedCategory === cat.value
                ? 'bg-slate-900 border-slate-900 text-white shadow-sm'
                : 'bg-white text-slate-600 hover:bg-slate-100 hover:text-slate-900'
            }`}
          >
            {cat.label}
          </button>
        ))}
      </div>

      {/* Insights Content Grid */}
      {loading ? (
        <div className="flex flex-col items-center justify-center min-h-[300px] gap-3">
          <Loader2 className="w-7 h-7 text-slate-400 animate-spin" />
          <p className="text-xs text-slate-500">Retrieving business analyses...</p>
        </div>
      ) : insights.length === 0 ? (
        <div className="max-w-md mx-auto pt-8">
          <InsightsEmptyState />
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {insights.map((insight) => (
            <InsightCard 
              key={insight.id} 
              insight={insight} 
              onPin={() => handlePin(insight.id)}
              onDelete={() => handleDelete(insight.id)}
            />
          ))}
        </div>
      )}
    </div>
  );
}
